services:
  postgres:
    image: postgres:15
    container_name: inventory_postgres
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
      POSTGRES_HOST_AUTH_METHOD: trust   # (không khuyến nghị trong môi trường thật)
      TZ: Asia/Ho_Chi_Minh               # hệ điều hành container
    command: ["postgres", "-c", "timezone=Asia/Ho_Chi_Minh"]  # <-- quan trọng
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_user -d inventory_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inventory_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory_app
    ports:
      - "8501:8501"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING:-false}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT:-}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY:-}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT:-inventory-text-to-sql}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=inventory_db
      - DB_USER=inventory_user
      - DB_PASSWORD=inventory_pass
    volumes:
      - ./data:/app/data
      - ./prompts:/app/prompts
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - inventory_network

volumes:
  postgres_data:

networks:
  inventory_network:
    driver: bridge
